In [9]:
import numpy as np

In [5]:
arr = np.zeros(10)


In [6]:
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
arr = np.ones(10)

In [8]:
arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [17]:
arr = []

In [18]:
arr

[]

In [19]:
arr = 5

In [2]:
arr = []
for i in range(9):
    arr.insert(i,0)

In [3]:
A = np.array(arr)

NameError: name 'np' is not defined

In [40]:
A 

array([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [18]:
arr = np.arange(10,51)

In [19]:
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [21]:
arr = np.arange(10,51,2)
arr

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [24]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [25]:
for i in range(3):
    for j in range(3):
        arr[i,j]=0
for i in range(3):
    for j in range(3):
        if i==j:
           arr[i,j]=1
arr

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [29]:
np.random.rand(1)

array([0.81274636])

In [31]:
np.random.rand(5,5)

array([[0.96864919, 0.57354348, 0.27169017, 0.41337345, 0.7157218 ],
       [0.82103646, 0.3993932 , 0.55476587, 0.52046162, 0.45190577],
       [0.18395355, 0.03622414, 0.90842398, 0.87503734, 0.41251444],
       [0.96189834, 0.65378505, 0.45133244, 0.57112892, 0.31726915],
       [0.21500808, 0.28226937, 0.08370339, 0.06602826, 0.74364543]])

In [33]:
np.random.rand(10,10)

array([[0.85848345, 0.6759393 , 0.19044176, 0.12185711, 0.42936146,
        0.36775526, 0.21726097, 0.62665738, 0.65942382, 0.05070687],
       [0.46881005, 0.8132907 , 0.87123757, 0.13253167, 0.33239153,
        0.26083098, 0.96550493, 0.78417988, 0.20555075, 0.73974531],
       [0.93084922, 0.55214497, 0.77755661, 0.94575605, 0.52462405,
        0.719096  , 0.51531998, 0.93885103, 0.96602744, 0.94815233],
       [0.66628967, 0.23431285, 0.2463396 , 0.47556312, 0.85956992,
        0.12825718, 0.86523103, 0.60936862, 0.075415  , 0.48823197],
       [0.39591119, 0.17526638, 0.277306  , 0.2843715 , 0.39061401,
        0.91579151, 0.93359417, 0.4347848 , 0.84959919, 0.02872976],
       [0.48160334, 0.09213271, 0.92781937, 0.9519018 , 0.35006495,
        0.52173033, 0.33824981, 0.43730562, 0.74970337, 0.77600883],
       [0.88983256, 0.47245136, 0.98352697, 0.96112143, 0.11445765,
        0.54926473, 0.61854278, 0.3713533 , 0.69587221, 0.18240013],
       [0.88192728, 0.25673932, 0.2626723

In [68]:
np.random.rand(20,size=(,dtype='l')

TypeError: rand() got an unexpected keyword argument 'dtype'