 NumPy Operations
 * Array with Array
 * Array with scalars
 * Universal Array Functions

In [3]:
import numpy as np

In [4]:
arr = np.arange(25).reshape(5,5)

In [5]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [7]:
arr = np.arange(1,11)

In [8]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [10]:
arr + arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [11]:
arr * arr

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [12]:
arr / arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [13]:
arr - 100

array([-99, -98, -97, -96, -95, -94, -93, -92, -91, -90])

In [14]:
arr ** 2

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [18]:
arr.mean()

5.5

In [19]:
arr.max()

10

In [21]:
arr.argmin()

0

In [22]:
arr.argmax()

9

In [23]:
arr.var()

8.25

In [26]:
import math
math.sqrt(arr.var())

2.8722813232690143

In [27]:
1/arr

array([1.        , 0.5       , 0.33333333, 0.25      , 0.2       ,
       0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ])

In [28]:
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [29]:
np.exp(arr)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04])

In [30]:
np.max(arr)

10

In [31]:
np.min(arr)

1

In [32]:
np.sin(arr)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111])

In [33]:
np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

In [34]:
np.var(arr)

8.25